const app = document.getElementById('app');

const demoItems = [
  {id:1,type:'FOUND',title:'Black Wallet',category:'Wallet / Purse',color:'Black',location:'Silent Study Area',date:'26 Aug 2026',status:'Active',description:'Black leather wallet found near the reading area.'},
  {id:2,type:'LOST',title:'Silver Water Bottle',category:'Bottle',color:'Silver',location:'Futsal Court',date:'25 Aug 2026',status:'Active',description:'Metallic silver bottle with a small sticker near the base.'},
  {id:3,type:'FOUND',title:'Blue Umbrella',category:'Accessories',color:'Blue',location:'School of Arts and Sciences (SAS)',date:'24 Aug 2026',status:'Active',description:'Foldable blue umbrella found near the entrance.'},
  {id:4,type:'LOST',title:'Wireless Earbuds Case',category:'Electronics',color:'White',location:'Cafeteria',date:'23 Aug 2026',status:'Resolved',description:'Small white charging case for wireless earbuds.'}
];

const FORM_CATEGORIES = ['Electronics','Wallet / Purse','Keys','Bottle','Books / Stationery','Clothing','Cards / ID','Accessories','Other'];
const FORM_COLORS = ['Black','White','Grey','Blue','Red','Green','Yellow','Brown','Silver','Gold','Multicolor','Other'];
const CAMPUS_LOCATIONS = [
  'School of Arts and Sciences (SAS)',
  'SAS — Big Fan Area',
  'School of Engineering and Applied Sciences (SEAS)',
  'SEAS — Airport Area',
  'Heritage School',
  'AMSOM Heritage Building',
  'AMSOM BK Building',
  'University Centre (UC)',
  'Student Lounge',
  'Silent Study Area',
  'Multipurpose Hall (MPH)',
  'Futsal Court',
  'Cafeteria',
  'Other / Not listed'
];
function optionList(values, selected=''){return values.map(v=>`<option value="${escapeHtml(v)}" ${v===selected?'selected':''}>${escapeHtml(v)}</option>`).join('');}
function locationOptions(selected=''){return optionList(CAMPUS_LOCATIONS, selected);}

let currentUser = JSON.parse(localStorage.getItem('lf_user') || 'null');
let activePage = location.hash.replace('#','') || (currentUser ? 'dashboard' : 'login');

function saveUser(user){currentUser=user;localStorage.setItem('lf_user',JSON.stringify(user));}
function logout(){localStorage.removeItem('lf_user');currentUser=null;navigate('login');}
function navigate(page){activePage=page;location.hash=page;render();window.scrollTo({top:0,behavior:'smooth'});}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}

function shell(content,title){return `<div class="app-shell">
<aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">LF</div><div><strong>Lost & Found</strong><span>Campus platform</span></div></div>
<nav>
<button class="${activePage==='dashboard'?'active':''}" onclick="navigate('dashboard')">⌂ <span>Dashboard</span></button>
<button class="${activePage==='browse'?'active':''}" onclick="navigate('browse')">⌕ <span>Browse & Search</span></button>
<button class="${activePage==='report-lost'?'active':''}" onclick="navigate('report-lost')">＋ <span>Report Lost</span></button>
<button class="${activePage==='report-found'?'active':''}" onclick="navigate('report-found')">＋ <span>Report Found</span></button>
<button class="${activePage==='reports'?'active':''}" onclick="navigate('reports')">▣ <span>My Reports</span></button>
<button class="${activePage==='notifications'?'active':''}" onclick="navigate('notifications')">♢ <span>Notifications</span></button>
<button class="${activePage==='settings'?'active':''}" onclick="navigate('settings')">⚙ <span>Settings</span></button>
</nav><div class="sidebar-bottom"><button onclick="navigate('help')">? <span>Help</span></button><button onclick="logout()">↪ <span>Log out</span></button></div></aside>
<main class="main"><header class="topbar"><button class="mobile-menu" onclick="document.getElementById('sidebar').classList.toggle('open')">☰</button><div><div class="eyebrow">Campus Lost & Found</div><h1>${escapeHtml(title)}</h1></div><div class="top-actions"><button class="icon-btn" onclick="navigate('notifications')">♢</button><button class="avatar" onclick="navigate('settings')">${escapeHtml((currentUser?.name||'S').charAt(0).toUpperCase())}</button></div></header><section class="content">${content}</section></main></div>`;}

function itemCard(item){return `<article class="item-card"><div class="item-image">${item.type==='LOST'?'?':'✓'}</div><div class="item-info"><div class="card-top"><span class="badge ${item.type.toLowerCase()}">${item.type}</span><span class="muted">${escapeHtml(item.date)}</span></div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.category)} · ${escapeHtml(item.location)}</p><div class="card-bottom"><span class="status">${escapeHtml(item.status)}</span><button class="text-btn" onclick="navigate('item-${item.id}')">View details →</button></div></div></article>`;}

function dashboard(){return shell(`<div class="hero"><div><span class="badge neutral">Welcome back</span><h2>Find it. Report it. Return it.</h2><p>One place to report lost items, report found items and search campus reports.</p></div><div class="hero-actions"><button class="btn primary" onclick="navigate('report-lost')">＋ Report Lost</button><button class="btn secondary" onclick="navigate('report-found')">＋ Report Found</button></div></div>
<div class="search-hero"><div><span class="eyebrow">Search retrieval</span><h3>Looking for something?</h3></div><div class="search-row"><input id="dashboard-search" placeholder="Search e.g. black wallet, bottle..." /><button class="btn primary" onclick="runDashboardSearch()">Search</button></div></div>
<div class="stats"><div class="stat"><span>Active reports</span><strong>8</strong></div><div class="stat"><span>Possible matches</span><strong>3</strong></div><div class="stat"><span>Resolved</span><strong>14</strong></div></div>
<div class="section-heading"><div><span class="eyebrow">Latest activity</span><h3>Recent reports</h3></div><button class="text-btn" onclick="navigate('browse')">View all →</button></div><div class="item-grid">${demoItems.slice(0,3).map(itemCard).join('')}</div>`, 'Dashboard');}
function runDashboardSearch(){localStorage.setItem('lf_query',document.getElementById('dashboard-search').value.trim());navigate('browse');}

function browse(){const q=localStorage.getItem('lf_query')||'';return shell(`<div class="page-intro"><span class="eyebrow">Search & retrieval</span><h2>Browse reports</h2><p>Search by keyword and narrow results with filters.</p></div><div class="filter-bar"><input id="browse-search" value="${escapeHtml(q)}" placeholder="Search item name, category or location..." oninput="filterItems()" /><select id="type-filter" onchange="filterItems()"><option value="">All types</option><option>LOST</option><option>FOUND</option></select><select id="category-filter" onchange="filterItems()"><option value="">All categories</option>${optionList(FORM_CATEGORIES)}</select><select id="color-filter" onchange="filterItems()"><option value="">All colors</option>${optionList(FORM_COLORS)}</select><select id="location-filter" onchange="filterItems()"><option value="">All locations</option>${locationOptions()}</select></div><div id="browse-results" class="item-grid"></div>`, 'Browse & Search') + `<script>setTimeout(filterItems,0)</script>`;}
function filterItems(){const r=document.getElementById('browse-results');if(!r)return;const q=(document.getElementById('browse-search')?.value||'').toLowerCase(),t=document.getElementById('type-filter')?.value||'',c=document.getElementById('category-filter')?.value||'',color=document.getElementById('color-filter')?.value||'',loc=document.getElementById('location-filter')?.value||'';const f=demoItems.filter(i=>(!q||`${i.title} ${i.category} ${i.location}`.toLowerCase().includes(q))&&(!t||i.type===t)&&(!c||i.category===c)&&(!color||i.color===color)&&(!loc||i.location===loc));r.innerHTML=f.length?f.map(itemCard).join(''):`<div class="empty"><div class="empty-icon">⌕</div><h3>No matching reports</h3><p>Try a broader keyword or remove a filter.</p></div>`;}
function reportForm(type){const lost=type==='LOST';return shell(`<div class="form-wrap"><div class="page-intro"><span class="eyebrow">${lost?'Lost item':'Found item'}</span><h2>Report ${lost?'a lost':'a found'} item</h2><p>${lost?'Tell the community enough to help identify your item.':'Provide useful details so the owner can recognise their item.'}</p></div><form class="form-card" onsubmit="submitReport(event,'${type}')"><div class="form-section"><h3>Basic information</h3><div class="two-col"><label>Item name *<input required name="title" placeholder="e.g. Black wallet" /></label><label>Category *<select required name="category"><option value="">Select category</option>${optionList(FORM_CATEGORIES)}</select></label></div><div class="two-col"><label>Color *<select required name="color"><option value="">Select color</option>${optionList(FORM_COLORS)}</select></label><label>${lost?'Last seen location':'Found location'} *<select required name="location"><option value="">Select campus location</option>${locationOptions()}</select></label></div><label>Description *<textarea required name="description" rows="4" placeholder="Brand, identifying marks, stickers, size, etc."></textarea></label></div><div class="form-section"><h3>When</h3><div class="two-col"><label>Date *<input required name="date" type="date" /></label><label>Approximate time<input name="time" type="time" /></label></div></div><div class="form-section"><h3>Images</h3><label>Item image <input id="image-input" name="image" type="file" accept="image/*" onchange="previewImage(event)" /></label><div id="image-preview" class="image-preview">Image preview will appear here.</div></div><div class="form-section"><h3>Contact preference</h3><label><input type="checkbox" checked /> Allow other users to contact me regarding this report</label></div><div class="form-actions"><button type="button" class="btn secondary" onclick="navigate('dashboard')">Cancel</button><button class="btn primary" type="submit">Submit ${lost?'Lost':'Found'} Report</button></div></form></div>`, `Report ${lost?'Lost':'Found'}`);}
function previewImage(e){const file=e.target.files[0],p=document.getElementById('image-preview');if(!file)return;const reader=new FileReader();reader.onload=x=>p.innerHTML=`<img src="${x.target.result}" alt="Selected item preview" />`;reader.readAsDataURL(file);}
function submitReport(e,type){e.preventDefault();const d=new FormData(e.target);alert(`${type==='LOST'?'Lost':'Found'} report submitted for "${d.get('title')}" at ${d.get('location')}. Demo only — no backend request was made.`);navigate('reports');}

function reports(){return shell(`<div class="section-heading"><div><span class="eyebrow">Your activity</span><h2>My Reports</h2><p>Track the reports you have submitted.</p></div><button class="btn primary" onclick="navigate('report-lost')">＋ New Report</button></div><div class="tabs"><button class="active">All</button><button>Lost</button><button>Found</button><button>Resolved</button></div><div class="item-grid">${demoItems.map(itemCard).join('')}</div>`, 'My Reports');}
function notifications(){return shell(`<div class="page-intro"><span class="eyebrow">Updates</span><h2>Notifications</h2><p>Keep track of possible matches and report activity.</p></div><div class="notification-list"><div class="notification unread"><strong>Possible match found</strong><p>A found item may match your "Silver Water Bottle" report.</p><span>10 minutes ago</span></div><div class="notification"><strong>Report submitted</strong><p>Your report was successfully recorded.</p><span>Yesterday</span></div><div class="notification"><strong>Welcome</strong><p>Your Lost & Found account is ready.</p><span>2 days ago</span></div></div>`, 'Notifications');}
function settings(){return shell(`<div class="page-intro"><span class="eyebrow">Account</span><h2>Settings</h2><p>Manage your profile and preferences.</p></div><div class="settings-grid"><form class="form-card" onsubmit="event.preventDefault();alert('Settings saved in demo mode.');"><h3>Profile</h3><label>Name<input value="${escapeHtml(currentUser?.name||'Student')}" /></label><label>Email<input value="${escapeHtml(currentUser?.email||'student@ahduni.edu.in')}" disabled /></label><button class="btn primary">Save changes</button></form><div class="form-card"><h3>Notifications</h3><label class="toggle"><input type="checkbox" checked /> Possible match alerts</label><label class="toggle"><input type="checkbox" checked /> Report updates</label><label class="toggle"><input type="checkbox" /> Email notifications</label><hr /><h3>Security</h3><button class="btn secondary" onclick="alert('Password reset flow would connect to the backend here.')">Change password</button></div></div>`, 'Settings');}
function help(){return shell(`<div class="page-intro"><span class="eyebrow">Guidelines</span><h2>How it works</h2><p>Quick guidance for using the platform responsibly.</p></div><div class="help-grid"><div class="info-card"><span>01</span><h3>Lost something?</h3><p>Report what you remember, add an image if possible, and keep your contact information up to date.</p></div><div class="info-card"><span>02</span><h3>Found something?</h3><p>Report where and when you found it. Avoid publishing sensitive identifying details that only the owner should know.</p></div><div class="info-card"><span>03</span><h3>Found a match?</h3><p>Use the details and appropriate contact flow to verify ownership before handing an item over.</p></div></div>`, 'Help & Guidelines');}
function itemDetails(id){const i=demoItems.find(x=>x.id===Number(id));if(!i)return shell(`<div class="empty"><h3>Item not found</h3></div>`,'Item Details');return shell(`<button class="text-btn back" onclick="navigate('browse')">← Back to search</button><div class="details"><div class="details-image">${i.type==='LOST'?'?':'✓'}</div><div class="details-body"><div class="card-top"><span class="badge ${i.type.toLowerCase()}">${i.type}</span><span class="status">${i.status}</span></div><h2>${escapeHtml(i.title)}</h2><p class="lead">${escapeHtml(i.description)}</p><dl><div><dt>Category</dt><dd>${escapeHtml(i.category)}</dd></div><div><dt>Location</dt><dd>${escapeHtml(i.location)}</dd></div><div><dt>Date</dt><dd>${escapeHtml(i.date)}</dd></div></dl><div class="form-actions"><button class="btn primary" onclick="alert('Demo: ownership/contact flow would open here.')">${i.type==='FOUND'?'I think this is mine':'View contact options'}</button><button class="btn secondary" onclick="navigate('browse')">Back</button></div></div></div>`, 'Item Details');}

function auth(page){const login=page==='login';return `<main class="auth-page"><div class="auth-brand"><div class="brand-mark">LF</div><strong>Lost & Found</strong></div><div class="auth-card"><span class="eyebrow">Campus platform</span><h1>${login?'Welcome back':'Create your account'}</h1><p>${login?'Sign in to manage reports and find items.':'Use your university email to get started.'}</p><form onsubmit="handleAuth(event,'${login?'login':'signup'}')">${!login?'<label>Full name<input name="name" required placeholder="Your name" /></label>':''}<label>University email<input name="email" type="email" required placeholder="student@ahduni.edu.in" /></label><label>Password<input name="password" type="password" required placeholder="••••••••" /></label>${!login?'<label>Confirm password<input name="confirm" type="password" required placeholder="••••••••" /></label>':''}${login?'<button type="button" class="text-btn forgot" onclick="alert(\'Demo: password recovery would be connected to the backend.\')">Forgot password?</button>':''}<button class="btn primary full">${login?'Log in':'Create account'}</button></form><div class="auth-switch">${login?'New here?':'Already have an account?'} <button class="text-btn" onclick="navigate('${login?'signup':'login'}')">${login?'Create an account':'Log in'}</button></div></div><p class="demo-note">Frontend demo · Authentication is simulated locally.</p></main>`;}
function handleAuth(e,mode){e.preventDefault();const d=new FormData(e.target);if(mode==='signup'&&d.get('password')!==d.get('confirm')){alert('Passwords do not match.');return;}saveUser({name:d.get('name')||d.get('email').split('@')[0],email:d.get('email')});navigate('dashboard');}

function render(){if(!currentUser&&!['login','signup'].includes(activePage))activePage='login';let h;if(activePage==='login'||activePage==='signup')h=auth(activePage);else if(activePage==='dashboard')h=dashboard();else if(activePage==='browse')h=browse();else if(activePage==='report-lost')h=reportForm('LOST');else if(activePage==='report-found')h=reportForm('FOUND');else if(activePage==='reports')h=reports();else if(activePage==='notifications')h=notifications();else if(activePage==='settings')h=settings();else if(activePage==='help')h=help();else if(activePage.startsWith('item-'))h=itemDetails(activePage.split('-')[1]);else h=currentUser?dashboard():auth('login');app.innerHTML=h;}
window.addEventListener('hashchange',()=>{activePage=location.hash.replace('#','')||(currentUser?'dashboard':'login');render();});
render();
